### ISSUE TITLE
Замечания по User Stories

### ISSUE THREAD

**Issue by nvamelichev** [nastygorodi/PROJECT-Short_Text_Generator#2]
- [x] Не соблюден формат User Stories ("Как <определённый, конкретный вид пользователя> я хочу <сделать то-то и то-то>  чтобы <конкретный полезный результат или избавление от конкретной проблемы/класса проблем>").
   - Смотрю в начало предложения: "Пользователь хочет..." - сразу вопрос, какой пользователь? Какие виды пользователей, как вы предполагаете, будут пользоваться проектом? (Пользователь "о, генератор смешных текстов, я пришёл посмеяться и уйти" - это не такой же пользователь, как "я журналист/блогер/инфлюенсер, и мне надо подобрать цепкий заголовок для статьи/ютуб-видео/блогпоста/...")
   - Почти нет обоснования, зачем нужна та или иная функциональность. Например, зачем ограничивать длину генерируемого текста? Чтобы генератор не работал слишком долго? Чтобы он не сгенерировал слишком бессвязный текст? Чтобы он не съел всю память?
- [x] "...чтобы генерация текста была максимально простой с точки зрения использования продукта" - довольно загадочная фраза. Начало ("Чтобы генерация текста была максимально простой") звучит более-менее логично, и даже можно придумать несколько вариантов как реализовать это требование (генерация текста одной кнопкой/одним вызовом консольной команды, быстрая генерация кучи текстов чтобы можно было использовать их в нескольких заголовках сразу, ...). А вот продолжение фразы ("...с точки зрения использования продукта") я не очень понял, и оно кажется, как минимум, избыточным. **Не бойтесь писать требования простыми словами** - вам же потом по этим требованиям нужно объектно-ориентированный дизайн будет придумывать :-)

Рекомендация: посмотрите [FAQ по требованиям](https://github.com/nvamelichev/hse-java-spring-2022/blob/main/requirements-faq.md). Там есть ссылки на хорошие ресурсы по User Stories, они помогут лучше сформулировать пользовательские/функциональные требования к продукту.

**Comment by vorobeevich** [comment]
Исправили! Извиняемся, что опоздали, просто этот маленький пункт не заметили.

**Comment by nvamelichev** [comment]
Ничего страшного!
Посмотрел, принято :+1:
