### ISSUE TITLE
Замечания по CRC-карточкам

### ISSUE THREAD

**Issue by nvamelichev** [nastygorodi/PROJECT-Short_Text_Generator#3]
- [x] Классу Headline, кажется, не хватает ответственности "разбить предложение на слова [и посчитать их частотность?]"
- [x] Класс Algorithm лучше переименовать, например, в [ShortText]Generator. Algorithm - слишком обобщённое название для класса, всё равно что для метода "processData" :-)
- [x] Предлагаю выделить в отдельные классы: логику работы со словарём (Vocabulary) и логику работы Марковской цепи использующей словарь (MarkovChain). В этом случае, класс Algorithm (ShortTextGenerator) станет "[фасадом](https://ru.wikipedia.org/wiki/Фасад_(шаблон_проектирования))", использующим Vocabulary и MarkovChain для генерации текстов.

В целом, замечания не критичные :+1:, так что уже можете приступать к уточнённому проектированию (UML-диаграммы).

**Comment by vorobeevich** [comment]
Здравствуйте! У нас несколько вопросов по поводу того, как организовать архитектуру классов в проекте.
1) У нас есть класс Headline, который позволяет хранить заголовок (по сути - предложение, просто массив строчек). Можно сделать у него поле Body, в котором заголовок и будет лежать. Далее, необходим метод splitSentence, который поможет разбить сырое предложение - обычное строчку - в наш заголовок. Есть ли разница, будет ли такой метод просто возвращать массив строчек, либо же он должен перезаписывать поле нашего класса Body (по сути, конструктор класса)? 
2) Похожий вопрос - при работе с файлом, мы получим оттуда сырой текст - набор предложений. Можно внутри метода extractText разделить его на сырые предложения, а дальше запускать метод splitSentence для получения объекта класса Headline и добавлять их в Text путем вызова метода addHeadline. Такая архитектура годится?
3) И тоже не совсем понятно, есть ли разница - мы можем сделать класс для работы с Марковскими цепями просто набором методов, которые, например, по тексту и словарю смогут нам вернуть следующее слово, либо же хранить в полях этого класса какой-то текст и какой-то словарь, и при запуске метода generateNextWord работать с ними. Иными словами, есть ли разница - хранить данные в полях либо же каждый раз передавать в метод? 
4) Аналогично, в классе Vocabular будет метод buildVocab, строящий по тексту частотный словарь - это, по сути, конструктор класса? Можно оставить такую архитектуру - храним в полях текст и словарь, и при вызове этого метода обновляем словарь?
5) При заполнении CRC карточек, если наш класс A работает в методе с классом B, который в свою очередь работает с классом C, нужно ли указывать что класс А в нашем методе работает с классом B? И что вообще подразумевается под Collaborators - классы, чьи методы / объекты мы используем? 
P.S. Столько вопросов, потому что непонятно, как правильно работать с классами, которые реализуют какой-то алгоритм - одно дело класс Машина, в котором очевидно нужны хранить данные в полях, а вот что хранить, если наш класс должен только что-то делать, не очень понятно.

**Comment by nvamelichev** [comment]
Немного обсудили ваши вопросы на семинаре, на то что не обсуждали &mdash; отвечу здесь :-)

----

> есть ли разница - хранить данные в полях либо же каждый раз передавать в метод?

Если каждый раз передавать данные в метод, у вас получится просто процедурное программирование на Java. Иногда это норм и оправданно, называется "утилитный класс" (utility class). У такого класса все методы статические, стейта (полей класса) нет, всё передаётся в аргументах метода. Например, класс `Collections` из JDK содержит кучу полезных методов по работе с коллекциями, например, сортировку списков.

Но в рамках **объектно-ориентированного** проектирования лучше делать классы с состоянием (полями), которые взаимодействуют с другими классами, а не просто принимают откуда-то какие-то кусочки данных и обрабатывают их :-)

> И что вообще подразумевается под Collaborators - классы, чьи методы / объекты мы используем?

Это классы, чьи методы вызывает ваш класс чтобы сделать что-то полезное (реализовать свою "ответственность"), да.

> а вот что хранить, если наш класс должен только что-то делать, не очень понятно.

Входные данные для этого "чего-то" что вы делаете, как минимум. Если вы можете делать это как-то по-разному, ещё настройки будут храниться ("умножать матрицы таким-то методом", например)
