### ISSUE TITLE
Замечания по CRC-карточкам №2 и по UML

### ISSUE THREAD

**Issue by nvamelichev** [nastygorodi/PROJECT-Short_Text_Generator#4]
- [x] В MarkovChain я бы добавил детерминизма (seed = изначальное состояния генератора случайных чисел)
- [x] UML-диаграмма классов: между MarkovChain и Vocabulary скорее агрегация, т.к. словари можно менять "на лету"
- [x] UML-диаграмма классов: добавить ассоциацию между классом File и его пользователями, на стрелочке можно написать `<<use>>`
- [x] UML стейт-машина: заменить на диаграмму последовательности (Sequence Diagram)

**Comment by vorobeevich** [comment]
В UML в диаграмме классов так же добавили ассоциацию между классом Генератор и классами Марковская цепь, Словарь - так как он их использует, аналогично тому что несколько классов используют класс Файл.

**Comment by vorobeevich** [comment]
Вопрос по UML диаграмме Sequence  Diagram:
- так как программа консольная, логично, что с пользователем взаимодействует консольный интерфейс. Но отдельный класс для него можно не делать, если работа очень простая?

**Comment by nvamelichev** [comment]
> так как программа консольная, логично, что с пользователем взаимодействует консольный интерфейс. Но отдельный класс для него можно не делать, если работа очень простая?

Да, можно в UML-модели несущественные для описания системы классы не показывать :-)
А вот если бы у вас взаимодействие с консолью было сложным (как, например, в консольной игре или read-eval-print loop'е калькулятора/интерпретатора языка программирования/...) - тогда бы пришлось его описывать.

**Comment by nvamelichev** [comment]
Удивился, почему у вас на диаграмме классов появились подписи `<>` у стрелочек. Оказалось, что я неправильный markdown написал, и вместо **`<<use>>`** ошибочно показывалось `<>`. Поправьте, пожалуйста, на `<<use>>` :-)

**Comment by nvamelichev** [comment]
> Решили не убирать часть диаграммы последовательности, где User, Console Interface - это же не критично?
Да, это не критично :-)

**Comment by nvamelichev** [comment]
Замечаний нет, CRC-карточки и UML-диаграммы приняты.

Можете приступать к написанию кода! Помните:
- 8 апреля &mdash; первый релиз, нужно будет показать самую первую версию вашего проекта, которая реализует хотя бы один, самый базовый и важный пользовательский сценарий;
- Совершенно точно, ваш реальный код на Java будет несколько отличаться от построенных вами моделей, даже подробных (UML). Это нормально, так и должно быть: код всегда подробнее и сложнее квадратиков и стрелочек, с помощью которых его объясняют живым людям :-)
